/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoopUpdateSheet.java
 *
 * Created on 23-Mar-2010, 1:33:25 AM
 */

package meadowvale;

import java.awt.Color;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import meadowvale.controllers.exceptions.NonexistentEntityException;
import meadowvale.entities.MvCoop;

/**
 *
 * @author Team Sierra
 */
public class CoopUpdateSheet extends javax.swing.JPanel {

    public JDialog dialogWindow;
    public JLabel label;
    public ArrayList<String[]> rowData;
    public ArrayList<MvCoop> coopData = new ArrayList<MvCoop>();
    public Application mvApp;
    public boolean updated = false;
    public String coopSearchPredicate;
    public JTable coopSearchTable;
    public AdminUI.MyDTM t;

    // Creates new form CoopUpdateSheet
    CoopUpdateSheet(Application mvApp, ArrayList<String[]> rowData,
            JLabel label, JTable coopSearchTable,
            String coopSearchPredicate) {
        this.label = label;
        this.rowData = rowData;
        this.mvApp = mvApp;
        this.coopSearchTable = coopSearchTable;
        this.coopSearchPredicate = coopSearchPredicate;
        this.t = (AdminUI.MyDTM)this.coopSearchTable.getModel();
        initComponents();
        prepare_sheet();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coopUpdateTable = new javax.swing.JTable();
        coopUpdate = new javax.swing.JButton();
        updateCancel = new javax.swing.JButton();
        coopUpdated = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 267));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 18));
        jLabel15.setText("Update Selected Co-op Job Postings");

        coopUpdateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(coopUpdateTable);

        coopUpdate.setFont(new java.awt.Font("Verdana", 1, 14));
        coopUpdate.setText("Update");
        coopUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coopUpdateActionPerformed(evt);
            }
        });

        updateCancel.setFont(new java.awt.Font("Verdana", 1, 14));
        updateCancel.setText("Cancel");
        updateCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCancelActionPerformed(evt);
            }
        });

        coopUpdated.setFont(new java.awt.Font("Verdana", 0, 14));

        exitButton.setFont(new java.awt.Font("Verdana", 1, 14));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(coopUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(updateCancel)
                        .addGap(18, 18, 18)
                        .addComponent(coopUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coopUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(coopUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCancelActionPerformed
        label.setText("Updates cancelled by the user.");
        label.setForeground(Color.red);
        this.dialogWindow.dispose();
}//GEN-LAST:event_updateCancelActionPerformed

    private void coopUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coopUpdateActionPerformed
        this.coopUpdateTable.selectAll();
        String confirm = "Do you want to update the job postings?";
        
        int selection = JOptionPane.showConfirmDialog(null,
                confirm, "Confirmation", 0);
        
        if (selection == 1){
            return;
        }

        updated = true;

        for (int i = 0; i < this.coopUpdateTable.getRowCount(); i++){
            MvCoop mvCoop = coopData.get(i);
            mvCoop.setYearNumber((String)this.coopUpdateTable.getValueAt(i, 0));
            mvCoop.setBusiness((String)this.coopUpdateTable.getValueAt(i, 1));
            mvCoop.setLocation((String)this.coopUpdateTable.getValueAt(i, 2));
            mvCoop.setActivity((String)this.coopUpdateTable.getValueAt(i, 3));
            mvCoop.setContact((String)this.coopUpdateTable.getValueAt(i, 4));
            mvCoop.setPhone((String)this.coopUpdateTable.getValueAt(i, 5));
            try {
                mvApp.MvCoopController.edit(mvCoop);

                List<MvCoop> coopList =
                        mvApp.selectEntitiesBy(MvCoop.class,
                        this.coopSearchPredicate);

                while (this.coopSearchTable.getRowCount() > 0){
                    t.removeRow(0);
                }

                if (coopList.isEmpty()){
                    t.addRow(new Object[] {"", "No Job Postings", " Matches Your",
                        "Search Terms.", "Please Try Again.", "",});
                }

                for (MvCoop newMvCoop : coopList){
                        t.addRow(new Object[] {newMvCoop.getYearNumber(),
                        newMvCoop.getBusiness(), newMvCoop.getLocation(),
                        newMvCoop.getActivity(), newMvCoop.getContact(),
                        newMvCoop.getPhone()});
                }

                this.coopUpdated.setText("Postings successfully updated." +
                        "Press Exit to quit.");
                this.coopUpdated.setForeground(Color.green);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(CoopUpdateSheet.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(CoopUpdateSheet.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_coopUpdateActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if (updated == false){
            label.setText("No updates is performed.");
            label.setForeground(Color.red);
        } else {
            label.setText("Update Successfully Completed.");
            label.setForeground(Color.green);
        }
        this.dialogWindow.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void prepare_sheet(){
        javax.swing.table.DefaultTableModel t =
                new javax.swing.table.DefaultTableModel();
        this.coopUpdateTable.setModel(t);
        t.addColumn ((Object)"Year");
        t.addColumn ((Object)"Business");
        t.addColumn ((Object)"Location");
        t.addColumn ((Object)"Activity");
        t.addColumn ((Object)"Contact");
        t.addColumn ((Object)"Phone Number");

        for (int i = 0; i < this.rowData.size(); i++){
            String[] oneRow = rowData.get(i);
            t.addRow(oneRow);
            String findCoop = "year_number = '" + oneRow[0] +
                    "' AND business = '" + oneRow[1] + "' AND location = '" +
                    oneRow[2] + "' AND activity = '" + oneRow[3] +
                    "' AND contact = '" + oneRow[4] + "' AND phone = '"
                    + oneRow[5] + "'";
            List<MvCoop> coopList =
                    mvApp.selectEntitiesBy(MvCoop.class, findCoop);
            MvCoop newCoop = coopList.get(0);
            this.coopData.add(newCoop);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coopUpdate;
    private javax.swing.JTable coopUpdateTable;
    private javax.swing.JLabel coopUpdated;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateCancel;
    // End of variables declaration//GEN-END:variables

}
